version: '3.8'
services:
  todotests:
    image: todotests
    restart: on-failure
    environment:
      - FRONT_HOST=todofront
    depends_on:
      - todofront
      - todoback
  todofront:
    image: todofrontend
    restart: on-failure
    environment:
      - REACT_APP_API_HOST=todoback
    depends_on:
      - todoback
    ports:
      - 3000:3000
  todoback:
    image: todobackend
    restart: on-failure
    ports:
      - 3001:3001